name: lukesitalsingh
favicon: null
layout_spectrum: 0.51543
typography_spectrum: 0.18531
title: LUKE SITAL-SINGH
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#16271f'
    - '#bda687'
    - '#ac3133'
    - '#f9f8f6'
    - '#6d4f33'
  brandStrength: 0.9375
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
