name: lukesitalsingh
favicon: null
layout_spectrum: 0.255
typography_spectrum: 0.51252
title: LUKE SITAL-SINGH
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#363636'
    - '#649db1'
    - '#b2af4e'
    - '#040301'
  brandStrength: 0.3442787791136652
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
