title: LUKE SITAL-SINGH
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 1
  lightness: 0
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#717171'
    - '#474747'
    - '#afaeaf'
  rhythmicContrast: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: lukesitalsingh
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.25209
layout_spectrum: 0.71953
