name: lukesitalsingh
favicon: null
layout_spectrum: 0.71953
typography_spectrum: 0.25209
title: LUKE SITAL-SINGH
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#717171'
    - '#474747'
    - '#afaeaf'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.6875
  rhythmicContrast: 0
purpose: []
